### ISSUE TITLE
Продолжение курса

### ISSUE THREAD

**Issue by khasanovsm** [mlcoursemm/mlcoursemm2019spring#1]
Здравствуйте 

Подскажите пожалуйста, будет ли курс в весеннем семестре 2020? Если да, то какое расписание?

**Comment by fatheral** [comment]
Будет. Но он будет в целом тем же самым, что и год назад, только добавится \ поменяется несколько практических заданий \ занятий.

По дате начала - примерно в середине февраля. Следите за обновлениями за репозиториями на этом аккаунте - mlcoursemm.

**Comment by khasanovsm** [comment]
👍 ждем-с
